name: Deploy static content to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and deploy
        run: |
          # Build your project here
          echo "Building project..."

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0 # Explicitly specify a version
        with:
          name: artifact-name
          path: path/to/artifact
